class Languages:

	language_list: dict[str, list[str]] = {
		"aa": ["Afar", "Afaraf"],
		"ab": ["Abkhaz", "аҧсуа бызшәа"],
		"ae": ["Avestan", "Avesta"],
		"af": ["Afrikaans", "Afrikaans"],
		"ak": ["Akan", "Akan"],
		"am": ["Amharic", "አማርኛ"],
		"an": ["Aragonese", "Aragonés"],
		"ar": ["Arabic", "اللغة العربية"],
		"as": ["Assamese", "অসমীয়া"],
		"av": ["Avaric", "авар мацӀ"],
		"ay": ["Aymara", "Aymar aru"],
		"az": ["Azerbaijani", "Azərbaycan dili"],
		"ba": ["Bashkir", "башҡорт теле"],
		"be": ["Belarusian", "беларуская мова"],
		"bg": ["Bulgarian", "български език"],
		"bh": ["Bihari", "भोजपुरी"],
		"bi": ["Bislama", "Bislama"],
		"bm": ["Bambara", "Bamanankan"],
		"bn": ["Bengali", "বাংলা"],
		"bo": ["Tibetan", "བོད་ཡིག"],
		"br": ["Breton", "Brezhoneg"],
		"bs": ["Bosnian", "Bosanski jezik"],
		"ca": ["Catalan", "Català"],
		"ce": ["Chechen", "нохчийн мотт"],
		"ch": ["Chamorro", "Chamoru"],
		"co": ["Corsican", "Corsu"],
		"cr": ["Cree", "ᓀᐦᐃᔭᐍᐏᐣ"],
		"cs": ["Czech", "Čeština"],
		"cu": ["Old Church Slavonic", "ѩзыкъ словѣньскъ"],
		"cv": ["Chuvash", "чӑваш чӗлхи"],
		"cy": ["Welsh", "Cymraeg"],
		"da": ["Danish", "Dansk"],
		"de": ["German", "Deutsch"],
		"dv": ["Divehi", "Dhivehi"],
		"dz": ["Dzongkha", "རྫོང་ཁ"],
		"ee": ["Ewe", "Eʋegbe"],
		"el": ["Greek", "Ελληνικά"],
		"en": ["English", "English"],
		"eo": ["Esperanto", "Esperanto"],
		"es": ["Spanish", "Español"],
		"et": ["Estonian", "Eesti"],
		"eu": ["Basque", "Euskara"],
		"fa": ["Persian", "فارسی"],
		"ff": ["Fula", "Fulfulde"],
		"fi": ["Finnish", "Suomi"],
		"fj": ["Fijian", "Vakaviti"],
		"fo": ["Faroese", "Føroyskt"],
		"fr": ["French", "Français"],
		"fy": ["Western Frisian", "Frysk"],
		"ga": ["Irish", "Gaeilge"],
		"gd": ["Scottish Gaelic", "Gàidhlig"],
		"gl": ["Galician", "Galego"],
		"gu": ["Gujarati", "ગુજરાતી"],
		"gv": ["Manx", "Gaelg"],
		"ha": ["Hausa", "هَوُسَ"],
		"he": ["Hebrew", "עברית"],
		"hi": ["Hindi", "हिन्दी"],
		"ho": ["Hiri Motu", "Hiri Motu"],
		"hr": ["Croatian", "Hrvatski"],
		"ht": ["Haitian", "Kreyòl ayisyen"],
		"hu": ["Hungarian", "Magyar"],
		"hy": ["Armenian", "Հայերեն"],
		"hz": ["Herero", "Otjiherero"],
		"ia": ["Interlingua", "Interlingua"],
		"id": ["Indonesian", "Bahasa Indonesia"],
		"ie": ["Interlingue", "Interlingue"],
		"ig": ["Igbo", "Asụsụ Igbo"],
		"ii": ["Nuosu", "ꆈꌠ꒿ Nuosuhxop"],
		"ik": ["Inupiaq", "Iñupiaq"],
		"io": ["Ido", "Ido"],
		"is": ["Icelandic", "Íslenska"],
		"it": ["Italian", "Italiano"],
		"iu": ["Inuktitut", "ᐃᓄᒃᑎᑐᑦ"],
		"ja": ["Japanese", "日本語"],
		"jv": ["Javanese", "basa Jawa"],
		"ka": ["Georgian", "ქართული"],
		"kg": ["Kongo", "Kikongo"],
		"ki": ["Kikuyu", "Gĩkũyũ"],
		"kj": ["Kwanyama", "Kuanyama"],
		"kk": ["Kazakh", "қазақ тілі"],
		"kl": ["Kalaallisut", "Kalaallisut"],
		"km": ["Khmer", "ខេមរភាសា"],
		"kn": ["Kannada", "ಕನ್ನಡ"],
		"ko": ["Korean", "한국어"],
		"kr": ["Kanuri", "Kanuri"],
		"ks": ["Kashmiri", "कश्मीरी"],
		"ku": ["Kurmanji (Kurdish)", "Kurmancî"],
		"kv": ["Komi", "коми кыв"],
		"kw": ["Cornish", "Kernewek"],
		"ky": ["Kyrgyz", "Кыргызча"],
		"la": ["Latin", "Latine"],
		"lb": ["Luxembourgish", "Lëtzebuergesch"],
		"lg": ["Ganda", "Luganda"],
		"li": ["Limburgish", "Limburgs"],
		"ln": ["Lingala", "Lingála"],
		"lo": ["Lao", "ລາວ"],
		"lt": ["Lithuanian", "Lietuvių Kalba"],
		"lu": ["Luba-Katanga", "Tshiluba"],
		"lv": ["Latvian", "Latviešu Valoda"],
		"mg": ["Malagasy", "Fiteny Malagasy"],
		"mh": ["Marshallese", "Kajin M̧ajeļ"],
		"mi": ["Māori", "te reo Māori"],
		"mk": ["Macedonian", "македонски јазик"],
		"ml": ["Malayalam", "മലയാളം"],
		"mn": ["Mongolian", "Монгол хэл"],
		"mr": ["Marathi", "मराठी"],
		"ms": ["Malay", "Bahasa Melayu"],
		"mt": ["Maltese", "Malti"],
		"my": ["Burmese", "ဗမာစာ"],
		"na": ["Nauru", "Ekakairũ Naoero"],
		"nb": ["Norwegian Bokmål", "Norsk bokmål"],
		"nd": ["Northern Ndebele", "isiNdebele"],
		"ne": ["Nepali", "नेपाली"],
		"ng": ["Ndonga", "Owambo"],
		"nl": ["Dutch", "Nederlands"],
		"nn": ["Norwegian Nynorsk", "Norsk Nynorsk"],
		"no": ["Norwegian", "Norsk"],
		"nr": ["Southern Ndebele", "isiNdebele"],
		"nv": ["Navajo", "Diné bizaad"],
		"ny": ["Chichewa", "chiCheŵa"],
		"oc": ["Occitan", "Occitan"],
		"oj": ["Ojibwe", "ᐊᓂᔑᓈᐯᒧᐎᓐ"],
		"om": ["Oromo", "Afaan Oromoo"],
		"or": ["Oriya", "ଓଡ଼ିଆ"],
		"os": ["Ossetian", "ирон æвзаг"],
		"pa": ["Panjabi", "ਪੰਜਾਬੀ"],
		"pi": ["Pāli", "पाऴि"],
		"pl": ["Polish", "Polski"],
		"ps": ["Pashto", "پښتو"],
		"pt": ["Portuguese", "Português"],
		"qu": ["Quechua", "Runa Simi"],
		"rm": ["Romansh", "Rumantsch Grischun"],
		"rn": ["Kirundi", "Ikirundi"],
		"ro": ["Romanian", "Română"],
		"ru": ["Russian", "Русский"],
		"rw": ["Kinyarwanda", "Ikinyarwanda"],
		"sa": ["Sanskrit", "संस्कृतम्"],
		"sc": ["Sardinian", "Sardu"],
		"sd": ["Sindhi", "सिन्धी"],
		"se": ["Northern Sami", "Davvisámegiella"],
		"sg": ["Sango", "Yângâ tî sängö"],
		"si": ["Sinhala", "සිංහල"],
		"sk": ["Slovak", "Slovenčina"],
		"sl": ["Slovenian", "Slovenščina"],
		"sn": ["Shona", "chiShona"],
		"so": ["Somali", "Soomaaliga"],
		"sq": ["Albanian", "Shqip"],
		"sr": ["Serbian", "српски језик"],
		"ss": ["Swati", "SiSwati"],
		"st": ["Southern Sotho", "Sesotho"],
		"su": ["Sundanese", "Basa Sunda"],
		"sv": ["Swedish", "Svenska"],
		"sw": ["Swahili", "Kiswahili"],
		"ta": ["Tamil", "தமிழ்"],
		"te": ["Telugu", "తెలుగు"],
		"tg": ["Tajik", "тоҷикӣ"],
		"th": ["Thai", "ไทย"],
		"ti": ["Tigrinya", "ትግርኛ"],
		"tk": ["Turkmen", "Türkmen"],
		"tl": ["Tagalog", "Wikang Tagalog"],
		"tn": ["Tswana", "Setswana"],
		"to": ["Tonga", "faka Tonga"],
		"tr": ["Turkish", "Türkçe"],
		"ts": ["Tsonga", "Xitsonga"],
		"tt": ["Tatar", "татар теле"],
		"tw": ["Twi", "Twi"],
		"ty": ["Tahitian", "Reo Tahiti"],
		"ug": ["Uyghur", "ئۇيغۇرچە‎"],
		"uk": ["Ukrainian", "Українська"],
		"ur": ["Urdu", "اردو"],
		"uz": ["Uzbek", "Ўзбек"],
		"ve": ["Venda", "Tshivenḓa"],
		"vi": ["Vietnamese", "Tiếng Việt"],
		"vo": ["Volapük", "Volapük"],
		"wa": ["Walloon", "Walon"],
		"wo": ["Wolof", "Wollof"],
		"xh": ["Xhosa", "isiXhosa"],
		"yi": ["Yiddish", "ייִדיש"],
		"yo": ["Yoruba", "Yorùbá"],
		"za": ["Zhuang", "Saɯ cueŋƅ"],
		"zh": ["Chinese", "中文"],
		"zu": ["Zulu", "isiZulu"],
		"ast": ["Asturian", "Asturianu"],
		"ckb": ["Sorani (Kurdish)", "سۆرانی"],
		"cnr": ["Montenegrin", "Crnogorski"],
		"jbo": ["Lojban", "la .lojban."],
		"kab": ["Kabyle", "Taqbaylit"],
		"kmr": ["Kurmanji (Kurdish)", "Kurmancî"],
		"ldn": ["Láadan", "Láadan"],
		"lfn": ["Lingua Franca Nova", "Lingua Franca Nova"],
		"sco": ["Scots", "Scots"],
		"sma": ["Southern Sami", "Åarjelsaemien Gïele"],
		"smj": ["Lule Sami", "Julevsámegiella"],
		"szl": ["Silesian", "ślůnsko godka"],
		"tok": ["Toki Pona", "Toki Pona"],
		"zba": ["Balaibalan", "باليبلن"],
		"zgh": ["Standard Moroccan Tamazight", "ⵜⴰⵎⴰⵣⵉⵖⵜ"]
	}
